apiVersion: v1
kind: Service
metadata:
  name: {{ include "minion.fullname" . }}
  labels:
    {{- include "minion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: karaf
      port: {{ .Values.service.karaf.port }}
      targetPort: karaf
      protocol: TCP
    {{- if .Values.prometheus.jmxExporter.enabled }}
    - name: prom-jmx
      port: {{ .Values.prometheus.jmxExporter.port }}
      targetPort: prom-jmx
      protocol: TCP
    {{- end }}
  selector:
    {{- include "minion.selectorLabels" . | nindent 4 }}
